### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by dasJ** [Icinga/icingadb#235]
I hate to be that guy but here I am - Is this dead?
The reason I'm asking is that when this project was announced I was in the process of replanning our Icinga cluster.
I wanted to wait for icingadb to mature a bit (or at least release a stable build), but the project seems to be dead by now, looking at the most recent commits and the PRs.
There are still major stability issues like #197 which are not fixed and prevent me from building the new cluster with icingadb - I'll stay with regular DB IDO for now which is sad because this project seems to be very promising.

So what's the goal with this? Are there any resources for keeping up the development or should we stick with DB IDO?

**Comment by N-o-X** [comment]
Hi @dasJ,

the project isn't dead, but has indeed not seen a lot of work in the past months. That's because all developers had to focus on critical Icinga 2 versions. But as of now we've already started to get back into Icinga DB development (e.g. #232 #221) and will continue doing so after Icinga 2 bug fix releases 2.11.7 and 2.12.2 last week. 

We're only a small team of developers, but Icinga DB is our highest priority besides keeping Icinga 2 healthy.

Greetings
Noah
