### ISSUE TITLE
Not all timestamps are stored in ms in the DB

### ISSUE THREAD

**Issue by Yonas-net** [Icinga/icingadb#357]
## Describe the bug

I don't know exactly what else is broken, but I tested `icinga2_start_time` and `Downtime` start & end time and noticed that the values are stored in seconds. Since Icinga DB Web still assumes that the timestamps are all in ms, they are incorrectly cast to seconds, which then leads to the wrong results. And since `Icinga2` always submitted it to `redis` in seconds even with v2.12.0, I don't think it' s Icinga2's bug, but rather icingadb's.

**Comment by Yonas-net** [comment]
Did just recheck it and noticed that there is no problem with manually(Icinga Web 2) created `Downtimes`, but only with configured `ScheduledDowntimes`.

```bash
apply Service "load" {
  import "generic-service"

  check_command = "load"

  /* Used by the ScheduledDowntime apply rule in `downtimes.conf`. */
  vars.backup_downtime = "02:00-03:00"

  assign where host.name == NodeName
}
```

```bash
apply ScheduledDowntime "backup-downtime" to Service {
  author = "icingaadmin"
  comment = "Scheduled downtime for backup"

  ranges = {
    monday = service.vars.backup_downtime
    tuesday = service.vars.backup_downtime
    wednesday = service.vars.backup_downtime
    thursday = service.vars.backup_downtime
    friday = service.vars.backup_downtime
    saturday = service.vars.backup_downtime
    sunday = service.vars.backup_downtime
  }

  assign where service.vars.backup_downtime != ""
}
```

**Icinga Web 2:**

<img width="842" alt="Bildschirmfoto 2021-08-24 um 10 46 52" src="https://user-images.githubusercontent.com/57616252/130586867-637ed99d-18ff-4ddb-aeb2-bf31e72bd164.png">

**Comment by Yonas-net** [comment]
> Did just recheck it and noticed that there is no problem with manually(Icinga Web 2) created `Downtimes`, but only with configured `ScheduledDowntimes`.

Sorry, I figured out today that the problem only affects downtimes which should be scheduled in the future.

**Comment by julianbrost** [comment]
I think the part about Downtimes is a bug in icingadb-web. `downtime.start_time` and `downtime.end_time` can be `NULL` and are only set if a downtime is in effect. icingadb-web handles `NULL` like timestamp `0` and therefore displays 1970-01-01. Instead, it should display some useful text instead. I'm not sure what the the best wording would be, something along the lines of "downtime not effective yet".

`icingadb_instance.icinga2_start_time` is indeed an absolute timestamp given in seconds instead of milliseconds. Given that this value is just passed from icinga2 (which does not convert this timestamp to ms in contrast to (hopefully) all the others). We'd have to fix this in icingadb if we don't want to have any "Icinga DB needs at least Icinga 2.13.3" requirements (but maybe we'll end  up with something like that anyways because of things like https://github.com/Icinga/icinga2/pull/8953). One option to fix this in icingadb would be to convert to milliseconds if the number it too low to be in milliseconds. This would allow fixing the icinga2 part to consistently write ms without having to change icingadb yet again. @Al2Klimov @N-o-X what do you think?

**Comment by Al2Klimov** [comment]
<details>
<summary>Wanna my absolutely honest opinion about the status quo?</summary>
This is fine.™
</details>

**Comment by N-o-X** [comment]
> `icingadb_instance.icinga2_start_time` is indeed an absolute timestamp given in seconds instead of milliseconds. Given that this value is just passed from icinga2 (which does not convert this timestamp to ms in contrast to (hopefully) all the others). We'd have to fix this in icingadb if we don't want to have any "Icinga DB needs at least Icinga 2.13.3" requirements (but maybe we'll end up with something like that anyways because of things like [Icinga/icinga2#8953](https://github.com/Icinga/icinga2/pull/8953)). One option to fix this in icingadb would be to convert to milliseconds if the number it too low to be in milliseconds. This would allow fixing the icinga2 part to consistently write ms without having to change icingadb yet again. @Al2Klimov @N-o-X what do you think?

I think we shouldn't use a quick fix in Icinga DB to resolve those things. Sure, having 2.13.x as a requirement for Icinga DB 1.0 is a bit ugly, but really just a version change in our installation documentation. In my opinion we should bite the bullet and make sure our timestamps and durations use the right time unit coming out of Icinga 2 and keep the code clean of quick fixes. In the worst case this will break some testing environments.

**Comment by julianbrost** [comment]
I'm closing this here as `icinga2_start_time` will be fixed in icinga2 (https://github.com/Icinga/icinga2/issues/8991) and downtime start/end should be fixed in icingadb-web (https://github.com/Icinga/icingadb-web/issues/342).
