### ISSUE TITLE
icingadb-redis missing from bullseye-testing

### ISSUE THREAD

**Issue by RincewindsHat** [Icinga/icingadb#414]
## Describe the bug

The package icingadb-redis is missing from the bullseye repository on packages.icinga.com

**Comment by RincewindsHat** [comment]
@htriem

**Comment by htriem** [comment]
That's correct - in comparison to IcingaDB itself the packages for IcingaDB Redis are in a released state and therefore they would be available in our bullseye-release repository. I've checked packages.icinga.com, the packages seem to be available there. 

Hope I could help!

**Comment by htriem** [comment]
Yes, I'd advise the same. 

As far as my understanding goes, the testing repository is for packages we don't provide full support for. IcingaDB itself is "only" at the release candidate stage, which is why it belongs there. IcingaDB Redis on the other hand is at a releaseable stage, why it doesn't belong in testing.
